theme: minima
title: TechNTech
author: Raj Patel
email: rockadfae@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here,I write about various technologies innovated in recent times 
  in the field of Artificial Intelligence

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
